name: cli
version: 0.2.0
versioned_at: 2026-10-08 12:31
description: Macrostates CLI public behavior and compatibility contract.
entrypoint: README.md
dependencies:
- name: meta
  version: 2.0.0
  constraint: compatible
- name: process
  version: 3.0.0
  constraint: compatible
- name: python-library-1
  version: 1.0.0
  constraint: compatible
